name: Docker Build and Push1

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t rocky141987/rocky:latest .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets. DOCKERHUB_TOKEN }}
    - name: Push Docker image to Docker Hub
      run: docker push  rocky141987/rocky:latest
